### ISSUE TITLE
Check random sample of owner companies

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#101]
What can we now about them (about their sectors) based on 1, name, 2, orbis, 3, google search?

**Comment by korenmiklos** [comment]
Please provide a 100 list for manual review.

**Comment by zaveczgergo** [comment]
https://docs.google.com/spreadsheets/d/11P5uxhxhbEMcRi0BPGL7Tr5tOimmfxdvDn4wZ8jDl2c/edit#gid=0
