### ISSUE TITLE
Take a random sample (n=20) of keep(3) (master: balance-small-clean, using: firm_panel) ever_foreign == 1 companies where hole1 >= 1 & hole1 != . - check in balance-small and opten 

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#163]

**Comment by korenmiklos** [comment]
Super. I just like to indent the lines between preserve and restore for readability.

**Comment by zaveczgergo** [comment]
Ok, I will do so next time. In the meantime we agreed to update the `merleg-LTS` in `merleg-expat` (having an updated `balance-small`), and see the holes (and also the updated list) after that. See #165.
