### ISSUE TITLE
Test `csdid` estimation speed for one outcome variable

### ISSUE THREAD

**Issue by korenmiklos** [korenmiklos/expat-analysis#184]
Take a representative specification from the set of regressions ans estimate using `csdid`. Look at outcome and measure time.

**Comment by zaveczgergo** [comment]
@korenmiklos 
I am clearly using `csdid` in a wrong way. Can you have a look at the relevant [log](https://github.com/korenmiklos/expat-analysis/blob/master/output/timer.log) file?

**Comment by zaveczgergo** [comment]
I just realized I did not use `notyet` for `csdid`, try the code with that.

**Comment by zaveczgergo** [comment]
`estat simple` not working for `csdid`

**Comment by korenmiklos** [comment]
Not sure if relevant, but csdid expects the gvar to be zero, not missing, when the group is not treated.

**Comment by zaveczgergo** [comment]
I used `mvencode first_year_foreign, mv(0)` now. Still I get `expression too long` as error message (`_rc == 130`).
I updated the do file though to make it run even after the error (see the log file in the commit).

**Comment by zaveczgergo** [comment]
See #198

**Comment by korenmiklos** [comment]
To keep it fair, you can reduce the number of reps in csdid, as well.

**Comment by zaveczgergo** [comment]
I just see (last time I checked was last week) they [updated](https://friosavila.github.io/playingwithstata/main_csdid.html) the package, I try `agg()` option after `csdid` instead of `estat`. It might reduce time.
I can not see an option to set reps.

**Comment by zaveczgergo** [comment]
@korenmiklos 
Now I run the `wboot` option. But all in all, 1, `csdid_stats _aggregator_type_` does not work for me, 2, `estat event` produces errors (`estimates post: matrix has missing values`). The first problem is manageable by using agg(_aggregator_type_) as an option for `csdid`. Regarding the second problem, old `csdid` could produce event time, the new one can not for these data.
At least `ATT` is comparable for `attgt` and `csdid`. Once the log file is ready with wboot, I discuss all the results here (should be done in an hour).

**Comment by zaveczgergo** [comment]
1, **command**: `attgt` - **type**: _event_ - **time**: _878_ - **result**: -
2, **command**: `attgt` - **type**: _att_ - **time**: _755_ - **result** _se in parentheses_: 0.241(0.052)
3, **command**: `csdid` with `agg(simple)` - **type**: _att_ - **time** _se in parentheses_: _2210_ - **result**: 0.327(0.092)
4, **command**: `csdid` with `estat(simple)` - **type**: _att_ - **time** _se in parentheses_: _2340_ - **result**: 0.327(0.092)
5, **command**: `csdid` - **type**: _att with wboost se_ - **time** _se in parentheses_: _2323_ - **result**: 0.327(0.085)
