### ISSUE TITLE
Implement new option for attgt: limitcontrol

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#189]

**Comment by korenmiklos** [comment]
No, the if clause has to be aware of what time we are looking at. An observation might be a good control for some g and t, but not others. Still not done.

**Comment by korenmiklos** [comment]
#212 will be more general

**Comment by korenmiklos** [comment]
For example, `limitcontrol(foreign == 0)`. The code should then enforce this condition for both `g` and `t`.

**Comment by korenmiklos** [comment]
`limitcontrol(expression)` is more natural. Let me do that in 1 more line.
