### ISSUE TITLE
Enter_year

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#19]
Enter_year seems to be problematic in many years. There are expats in 1949. For the time-being we moved enter_year for those expats who were there two or more years before the first foreign owner at a given company.

d6f0218594f642952c783d97e4b83666bdabad08

**Comment by korenmiklos** [comment]
`enter_year` can be 1949. This means person is there since 1949, even if we do not know anything about the firm in the early period.
