### ISSUE TITLE
Discuss why coefficients change a lot if a different set of depvars is used

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#197]

**Comment by zaveczgergo** [comment]
@korenmiklos 
After running the regressions with new depvars (`lnQL TFP_cd lnK lnIK_0 lnL exporter lnQ lnQh lnEx`), the coefficients change a lot compared to the old table (where depvars are `lnQ lnQL TFP_cd lnK lnL lnKL exporter`).
So instead of `attgt lnQL TFP_cd lnK lnIK_0 lnL exporter lnQ lnQh lnEx` I tried `foreach depvar in lnQL TFP_cd lnK lnIK_0 lnL exporter lnQ lnQh lnEx {attgt depvar}`. Results are totally different now: see varlist [version](https://github.com/korenmiklos/expat-analysis/blob/master/output/table_attgt.txt) and loop version [log](https://github.com/korenmiklos/expat-analysis/blob/master/output/est_attgt_loop.log) file (I have to rerun things because the code stopped now, so the loop txt hopefully will be ready tomorrow).
My guess is that the sample for `attgt varlist` is the intersection for all dependent variables. But I am not sure.
What should I do? Álmos asked for a lot of further specifications (`>= 2002`, `att`, `pre and post between abs(8)` ), should I run them as `attgt varlist` or as `foreach var of varlist {attgt var}`? The latter seems to be the correct one, it runs for more time though (for almost all day today for the 9 (depvars) * 3 (treatments) * 2 (ever_foreign and ever_foreign_hire) specifications).

**Comment by korenmiklos** [comment]
Indeed attgt varlist uses the sample where _all_ variables are nonmissing. The problem is likely log exports. You are using the sample of exporters where exports > 0. Drop this variable and check.

**Comment by zaveczgergo** [comment]
Álmos asked for nine variables: `lnQL TFP_cd lnK lnIK_0 lnL exporter lnQ lnQh lnEx`. Out of these nine variables the three new ones he proposed all have a lot of missing values: `lnIK_0 lnQh lnEx`. Thus, I left them out of the `attgt varlist` version but included them in the loop version.
For the `attgt varlist` with the six original variables, please [see](https://github.com/korenmiklos/expat-analysis/blob/master/output/table_attgt.txt).
For the loop version with all nine variables (both the six original and the three additional), please [see](https://github.com/korenmiklos/expat-analysis/blob/master/output/table_attgt_loop.txt).
How should we proceed? The loop takes more time to run if you look at the log files. Should I run the six original as `attgt varlist` and the other three in a loop for further specifications?
