### ISSUE TITLE
limit estimation of gt by pre and post

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#209]

**Comment by zaveczgergo** [comment]
1, Results are strange (more significant) in mostly all new specifications (that might be related to changing `foreign_hire` and `has_expat` as well) - for main results see: [this with depvars without missing values](https://github.com/korenmiklos/expat-analysis/blob/master/output/table_attgt.txt) and [this with depvars with missing values](https://github.com/korenmiklos/expat-analysis/blob/master/output/table_attgt_loop.txt).
2, The lastly commited files did not run, please see the [two](https://github.com/korenmiklos/expat-analysis/blob/master/output/est_attgt_att5.log) [log](https://github.com/korenmiklos/expat-analysis/blob/master/output/est_attgt_loop_att5.log)-s for the error message (a similar [specification](https://github.com/korenmiklos/expat-analysis/blob/master/output/est_attgt_att4.log) did run with old attgt).

**Comment by korenmiklos** [comment]
This is a bug. `att` would like to aggregate all ATTs, including those that have not been computed, because outside event window. Fixing now.

**Comment by korenmiklos** [comment]
Oh, actuall `att` may average pre periods as well, which it should not do!
