### ISSUE TITLE
check csdid ipw

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#219]
possible solution here: drop if missing(idepvars)

**Comment by korenmiklos** [comment]
https://causalinf.substack.com/p/a-tale-of-time-varying-covariates

**Comment by korenmiklos** [comment]
What I learned: IPW is *not* matching. It is a nonparametric way of controlling for covariates. It relies on having a well specified model of the propensity score. It does *not* only weight controls.

**Comment by korenmiklos** [comment]
If we want to include controls, we need to implement either IPW or DR, which are way more complex than anything we've done so far. Or switch to `csdid`.

**Comment by korenmiklos** [comment]
Sorry, I checked the theory, but @zaveczgergo pls check the actual estimation results.

**Comment by zaveczgergo** [comment]
@korenmiklos 
When using `method(reg)` with controls (both continuous and factor), the code runs, see [log](https://github.com/korenmiklos/expat-analysis/blob/master/output/est_csdid_att_idepvar.log). The controls are `lnL_sq lnQ_sq lnK_sq exporter_before i.year i.teaor08_2d`. 

When using `method(ipw)` without controls, the code runs, see [log](https://github.com/korenmiklos/expat-analysis/blob/master/output/est_csdid_att_ipw.log).

When using `method(ipw)` with controls (both continuous and factor), the code does not run. The controls are `lnL_sq lnQ_sq lnK_sq exporter_before i.year i.teaor08_2d`. If I take out `i.year i.teaor08_2d` the code runs. But I guess we want those controls.
