### ISSUE TITLE
try treatment2 in attgt

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#221]
`has_expat` vs `foreign_hire_only`

**Comment by zaveczgergo** [comment]
on efh sample

**Comment by korenmiklos** [comment]
Cherry pick c681af and try again.

**Comment by zaveczgergo** [comment]
Sorry, I could not figure out an error message for a while with `cherry-pick`. But `git reset` solved the issue. So I updated the results.
