### ISSUE TITLE
Create event study graph for `RperK`

### ISSUE THREAD

**Issue by korenmiklos** [korenmiklos/expat-analysis#236]
https://github.com/korenmiklos/expat-analysis/blob/master/code/estimate/event_studies.do

**Comment by zaveczgergo** [comment]
I tried just to add `RperK` to `local vars lnL lnQL lnK exporter` but it crashed with `graph RperK not found`.
So then I just tried to run the original `event_studies.do` but it crashes with `graph lnL not found` in `event_study_plot.do`.
I try to investigate the reasons.

**Comment by zaveczgergo** [comment]
I added `RperK` and `TFP_cd` and it runs now. I have no clue what I messed up before. Maybe I added a space in the local.

**Comment by korenmiklos** [comment]
@zaveczgergo please try without the `ipw` option see if the graphs have fewer zeros.

**Comment by korenmiklos** [comment]
If you have time, please rerun this and `TFP_cd` with `ipw(lnQ lnL exporter)` with new `attgt` (version 0.2.2)
