### ISSUE TITLE
Enter_year and first_year_foreign decisions

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#24]
Currently if someone is an expat before 1990, we recode him to be local.

In the remaining cases, if someone is an expat and his enter_year is less than the first year his company becomes foreign: 1, we recode foreign if the difference is one year - we move foreign to enter_year; 2, we recode enter_year if the difference is two years or more - we move enter_year to the first year of foreign.

Álmos suggests to stick to either to method 1 or 2 in all the cases no matter what the difference between enter_year and first_year_foreign in years is. The question is to which (**Decision 1**).

Besides, for the time-being first_exit_year had to be changed as well as is certain cases it was lower than enter_year after doing the former modifications. I moved enter_year to first_exit_year for the time-being. Based on the decision we make earlier, this problem may vanish, if it does not, we have to decide what to move: enter_year or first_exit_year (**Decision 2**).

**Comment by korenmiklos** [comment]
Can you send me seven frame ids where this problem happens? (Expat entering sooner than foreign. )

**Comment by zaveczgergo** [comment]
Currently there is none because of my modifications, but from the original settings here are seven relevant examples: ft10059610, ft10202289, ft10271322, ft10306273, ft10341755, ft10592229, ft12395176 (although e.g. the last one is greenfield in the sense that in the first year it appears in the database, in 2000, it is foreign; but on the other hand, the first expat year is 1998 because for an expat that is the enter year variable).

**Comment by korenmiklos** [comment]
The first couple of these example seem legit expat/foreign firms. Our new algorithm should handle them well.
