### ISSUE TITLE
Create event time graphs

### ISSUE THREAD

**Issue by zaveczgergo** [korenmiklos/expat-analysis#95]

**Comment by zaveczgergo** [comment]
@korenmiklos 
I can not get the estimates for `event_study.do`. I would need those to build and experiment with the code for the graph. My `Makefile` crashed at `trade.do` because `export_rauch` is missing from the `trade-country-firm.dta`.

**Comment by korenmiklos** [comment]
Did you check a `bead input update`?

**Comment by zaveczgergo** [comment]
Yes, it said: `Skipping update of trade-firm-panel: it is already at requested version (2021-02-09 17:17:18.255743+01:00)`
I checked and `export_rauch`, `import_rauch`, `export_consumer` and `import_consumer` are missing.
For the time-being I just generated those four variables as 0 (`gen `var` = 0) in `trade.do`, so `Makefile` runs and I could get to the estimates (even if they are clearly false). But technically I can work on the graphs, and I will only commit the `graph.do`, will not commit any of these made up changes.

**Comment by korenmiklos** [comment]
Fine, I need the code not the graph.

**Comment by korenmiklos** [comment]
This is a `bead` error. If there are already files there, and the meta is up to date, it does not load new bead. To force load, use
```
bead input delete trade-firm-panel
bead input add trade-firm-panel
```

**Comment by korenmiklos** [comment]
@zaveczgergo

**Comment by zaveczgergo** [comment]
Ok, I will try tomorrow morning.

**Comment by zaveczgergo** [comment]
> bead input add trade-firm-panel

Great, thanks it worked out!
